### ISSUE TITLE
Hitting with 500 Error

### ISSUE THREAD

**Issue by RiyaMRoy04** [IBM/virtualhelpdesk#9]
Hitting with 500 Error while creating a ticket in MAXIMO/IBM Control Desk.

![screen shot 2018-08-01 at 8 52 23 pm](https://user-images.githubusercontent.com/11567379/43586331-fca04e78-9684-11e8-832a-54d525775331.png)

![screen shot 2018-08-01 at 8 52 56 pm](https://user-images.githubusercontent.com/11567379/43586339-00d1d4b2-9685-11e8-9239-53920d5d321e.png)

Any workaround?

**Comment by stevemar** [comment]
@lee-zhg can you assist?

**Comment by lee-zhg** [comment]
I noticed the issue last week and am working to find a solution. It appears that the last Maximo/ICD system has different default configuration when you setup a new system.

**Comment by lee-zhg** [comment]
@RiyaMRoy04 It should work now. Maximo/ICD default behavior was changed recently.

Changes were made in app.js, .env.example and README.md.
